# src/main/resources/application.yml
   
server:
  servlet:
    context-path: /cmc
    register-default-servlet: true
  tomcat:
    relaxed-query-chars: "|,{,},[,]"
  port: 5001
  ssl:
    key-store: ${KEYSTORE_LOCATION}/TomcatJava17.jks
    key-store-password: ${KEYSTORE_PASS}
    enabled: true
 
management:
  info:
    env:
      enabled: true
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      discovery:
        enabled: true
      exposure:
        include: "info,health,refresh"
  endpoint:
    info:
      enabled: true
    refresh:
      enabled: true
    health:
      enabled: true